# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: ruby:2.6

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
      - run: git config user.email "hiroi+circleci@users.noreply.github.com"
      - run: git config user.name "hiroi+circleci"
      - run: bash -xe diff_commit.sh
      - run: git push origin master

filtersBranchesOnlyMaster: &filtersBranchesOnlyMaster
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          <<: *filtersBranchesOnlyMaster
          cron: "0 * * * *"
      - schedule:
          <<: *filtersBranchesOnlyMaster
          cron: "15 * * * *"
      - schedule:
          <<: *filtersBranchesOnlyMaster
          cron: "30 * * * *"
      - schedule:
          <<: *filtersBranchesOnlyMaster
          cron: "45 * * * *"
    jobs:
      - build
